*                     \PR:SAPLACEPS3\FO:FILL_PS_LINE_ITEM_PER
*** AA 17.05.2019 lang,j.: Manuelle Abgrenzung
DATA: LV_DATUM TYPE DATS.
DATA: LV_REFKEY Type ACE_OBJ_ID. " 6500000009 schmelzer,t.

MOVE IS_ITEM-LASTEFFDATE TO LV_DATUM.

SELECT SINGLE REF_KEY FROM ACESOBJ INTO LV_REFKEY WHERE OBJID EQ IS_ITEM-OBJID. " 6500000009 schmelzer,t. Get REF_KEY to select in next step from ACESOBJ_ASSGMT
SELECT SINGLE SGTXT FROM ACESOBJ_ASSGMT INTO CS_DOCITEM-SGTXT WHERE COMP EQ IS_ITEM-COMP AND REF_KEY EQ LV_REFKEY AND DATE_TO > LV_DATUM. " 6500000009 schmelzer,t.
*SELECT SINGLE SGTXT FROM ACESOBJ_ASSGMT INTO CS_DOCITEM-SGTXT WHERE COMP EQ IS_ITEM-COMP AND OBJID EQ IS_ITEM-OBJID AND DATE_TO > LV_DATUM.
